name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: cmake test
      run: cmake test
    - name: make test
      run: make -C test
    - name: run test
      run: ./test/runTest
