name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install cmake & libgtest-dev
      run: sudo apt-get install cmake libgtest-dev 
    - name: cmake gtest
      working-directory: /usr/src/gtest/
      run: |
        sudo cmake .
        sudo make
        sudo cp *.a /usr/lib
    - name: cmake test
      working-directory: /home/runner/work/testing-boilerplate/testing-boilerplate/
      run: cmake test  
    - name: make test
      working-directory: /home/runner/work/testing-boilerplate/testing-boilerplate/test
      run: make
    - name: run test
      working-directory: /home/runner/work/testing-boilerplate/testing-boilerplate/test
      run: ./test/runTest
